export const API_URL = "https://jsonplaceholder.typicode.com"
export const LS_ACCESS_TOKEN = "@access_token"
export const LS_REFRESH_TOKEN = "@refresh_token"
export const PAGE_LOGIN = "/login"
export const PAGE_TEST = "/test"